[phases.setup]
nixPkgs = ["php82", "composer", "nodejs-18_x"]

[phases.build]
cmds = [
  "composer install --optimize-autoloader --no-interaction",
  "php artisan key:generate --force",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

[variables]
PHP_EXTENSION_INTL = "1"
PHP_EXTENSION_ZIP = "1"
PHP_EXTENSION_SODIUM = "1"
PHP_EXTENSION_GD = "1"
PHP_EXTENSION_IMAGICK = "1"

